# uncomment this if you have mold linker installed

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/clang"
rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

[profile.release]
strip = true
opt-level= "s"
lto = true
codegen-units = 1
